# Generated by Django 5.0.7 on 2024-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
            ],
        ),
    ]
